services:
  db:
    image: postgres:15-alpine
    container_name: hw-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ hw-net ]
    logging:
      driver: "json-file"
      options:
        max-size: "5K"     # rotate when log reaches 10 MB
        max-file: "5"     

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw-app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: [ hw-net ]
    logging:
      driver: "json-file"
      options:
        max-size: "5K"
        max-file: "5"

networks:
  hw-net:
    driver: bridge

volumes:
  pgdata:
