server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres123}
  jpa:
    hibernate:
      ddl-auto: none         # Flyway manages schema
    properties:
      hibernate:
        jdbc.time_zone: Asia/Kolkata   # Force IST at JDBC layer
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    dev.harborwatch: INFO
